import type { WebNotification } from "@/types/notification";
import type { ScheduledTask } from "@/types/scheduled-task";
import type { TaskRun } from "@/types/task-run";

const now = new Date();
const minutesAgo = (minutes: number) => new Date(now.getTime() - minutes * 60_000).toISOString();
const minutesAfter = (minutes: number) => new Date(now.getTime() + minutes * 60_000).toISOString();

export const scheduledTasks: ScheduledTask[] = [
  { id: "task_001", userId: "user_001", name: "Morning Daily Brief", type: "Daily Brief", scheduleType: "Daily", cronExpression: "0 8 * * *", time: "08:00", timezone: "Asia/Bangkok", dataSources: ["News", "Weather API"], gptActions: ["Summarize", "Analyze Priority", "Recommend Action"], outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"], minPriorityScore: 70, status: "Active", isActive: true, lastRunAt: minutesAgo(80), nextRunAt: minutesAfter(520), createdAt: minutesAgo(4000), updatedAt: minutesAgo(80) },
  { id: "task_002", userId: "user_001", name: "สินค้าใหม่/น่าสนใจทั่วโลก", type: "Sale Monitor", scheduleType: "Hourly", cronExpression: "0 * * * *", time: null, timezone: "Asia/Bangkok", dataSources: ["Global Product Radar"], gptActions: ["Analyze Priority", "Generate Caption", "Recommend Action"], outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"], minPriorityScore: 70, status: "Active", isActive: true, lastRunAt: minutesAgo(17), nextRunAt: minutesAfter(43), createdAt: minutesAgo(3500), updatedAt: minutesAgo(17) },
  { id: "task_003", userId: "user_001", name: "US Stock News", type: "US Stock News", scheduleType: "Daily", cronExpression: "0 7 * * 1-5", time: "07:00", timezone: "Asia/Bangkok", dataSources: ["US Stock News"], gptActions: ["Summarize", "Analyze Priority", "Recommend Action"], outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"], minPriorityScore: 60, status: "Active", isActive: true, lastRunAt: minutesAgo(1440), nextRunAt: minutesAfter(2880), createdAt: minutesAgo(6000), updatedAt: minutesAgo(1440) },
  { id: "task_004", userId: "user_001", name: "Important Email Monitor", type: "Email Monitor", scheduleType: "Hourly", cronExpression: "*/30 * * * *", time: null, timezone: "Asia/Bangkok", dataSources: ["Gmail"], gptActions: ["Summarize", "Analyze Priority", "Recommend Action"], outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"], minPriorityScore: 80, status: "Active", isActive: true, lastRunAt: minutesAgo(36), nextRunAt: minutesAfter(24), createdAt: minutesAgo(7200), updatedAt: minutesAgo(36) },
  { id: "task_005", userId: "user_001", name: "Concert Alerts Near Me", type: "Concert Alerts", scheduleType: "Daily", cronExpression: "0 20 * * *", time: "20:00", timezone: "Asia/Bangkok", dataSources: ["Concert API"], gptActions: ["Summarize", "Analyze Priority", "Recommend Action"], outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"], minPriorityScore: 75, status: "Active", isActive: true, lastRunAt: minutesAgo(2880), nextRunAt: minutesAfter(1200), createdAt: minutesAgo(7000), updatedAt: minutesAgo(1000) },
  { id: "task_006", userId: "user_001", name: "Football Recap Nightly", type: "World Cup Recap", scheduleType: "Daily", cronExpression: "0 23 * * *", time: "23:00", timezone: "Asia/Bangkok", dataSources: ["Football API"], gptActions: ["Summarize", "Generate Caption", "Recommend Action"], outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"], minPriorityScore: 65, status: "Active", isActive: true, lastRunAt: minutesAgo(240), nextRunAt: minutesAfter(1140), createdAt: minutesAgo(9000), updatedAt: minutesAgo(240) },
  { id: "task_007", userId: "user_001", name: "Lifestyle Ideas", type: "Lifestyle Ideas", scheduleType: "Weekly", cronExpression: "0 10 * * 6", time: "10:00", timezone: "Asia/Bangkok", dataSources: ["Lifestyle", "Restaurants", "Cafe", "Weekend Ideas"], gptActions: ["Summarize", "Analyze Priority", "Recommend Action"], outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"], minPriorityScore: 55, status: "Active", isActive: true, lastRunAt: minutesAgo(3000), nextRunAt: minutesAfter(3600), createdAt: minutesAgo(9400), updatedAt: minutesAgo(3000) },
];

export const taskRuns: TaskRun[] = [
  { id: "run_001", taskId: "task_001", status: "success", startedAt: minutesAgo(80), finishedAt: minutesAgo(79), rawInput: { news: ["AI tools update", "Global news summary"], weather: "Bangkok is cloudy with afternoon rain risk." }, gptPrompt: "Summarize morning updates.", gptOutput: { title: "Morning Daily Brief", summary: "วันนี้มีข่าวโลกและสภาพอากาศที่ควรรู้", priority_score: 82, recommended_action: "อ่านข่าวสำคัญก่อนเริ่มงาน", caption: "Morning Daily Brief", image_prompt: null }, priorityScore: 82, telegramStatus: "mock_sent", errorMessage: null },
  { id: "run_002", taskId: "task_002", status: "success", startedAt: minutesAgo(18), finishedAt: minutesAgo(17), rawInput: { products: ["AI wearable", "E-ink dashboard", "Portable monitor"] }, gptPrompt: "Analyze global innovation products.", gptOutput: { title: "สินค้าใหม่/น่าสนใจทั่วโลก", summary: "พบสินค้าเทคโนโลยีและนวัตกรรมที่น่าสนใจจากทั่วโลก", priority_score: 84, recommended_action: "อ่านรายละเอียดใน Data Library", caption: "Global Product Radar", image_prompt: null }, priorityScore: 84, telegramStatus: "mock_sent", errorMessage: null },
  { id: "run_003", taskId: "task_004", status: "success", startedAt: minutesAgo(36), finishedAt: minutesAgo(35), rawInput: { gmail: ["Security alert", "Invoice reminder", "Meeting summary"] }, gptPrompt: "Summarize daily emails.", gptOutput: { title: "Daily Email Digest", summary: "สรุปอีเมลรายวัน แยกหมวดและความสำคัญ", priority_score: 88, recommended_action: "ตรวจอีเมลสำคัญก่อน", caption: "Daily Email Digest", image_prompt: null }, priorityScore: 88, telegramStatus: "mock_sent", errorMessage: null },
  { id: "run_004", taskId: "task_003", status: "success", startedAt: minutesAgo(1440), finishedAt: minutesAgo(1439), rawInput: { market: ["US tech company update", "Cloud software update", "Semiconductor update"] }, gptPrompt: "Summarize US Stock News.", gptOutput: { title: "US Stock News", summary: "สรุปข่าวหุ้นสหรัฐและกลุ่มเทคที่น่าติดตาม", priority_score: 84, recommended_action: "อ่านรายละเอียดใน Data Library ข้อมูลนี้เป็นข่าวเพื่ออ่านต่อ", caption: "US Stock News", image_prompt: null }, priorityScore: 84, telegramStatus: "mock_sent", errorMessage: null },
  { id: "run_005", taskId: "task_006", status: "success", startedAt: minutesAgo(240), finishedAt: minutesAgo(239), rawInput: { football: ["Thai football update", "World Cup update", "Premier League update"] }, gptPrompt: "Summarize football news.", gptOutput: { title: "Football Recap", summary: "สรุปข่าวบอลไทย บอลโลก และลีกใหญ่", priority_score: 72, recommended_action: "อ่านรายละเอียดเต็มใน Data Library", caption: "Football Recap", image_prompt: null }, priorityScore: 72, telegramStatus: "mock_sent", errorMessage: null },
  { id: "run_006", taskId: "task_005", status: "success", startedAt: minutesAgo(2880), finishedAt: minutesAgo(2879), rawInput: { concerts: ["Bangkok live event", "Thailand concert watch"] }, gptPrompt: "Summarize Thailand concerts.", gptOutput: { title: "Thailand Concert Alerts", summary: "มีคอนเสิร์ตในไทยที่น่าสนใจ", priority_score: 78, recommended_action: "ดูวันขายบัตรและสถานที่", caption: "Thailand Concert Alerts", image_prompt: null }, priorityScore: 78, telegramStatus: "mock_sent", errorMessage: null },
  { id: "run_007", taskId: "task_007", status: "success", startedAt: minutesAgo(3000), finishedAt: minutesAgo(2998), rawInput: { lifestyle: ["Bangkok cafe idea", "Buffet deal watch", "Short weekend activity"] }, gptPrompt: "Summarize lifestyle ideas.", gptOutput: { title: "Lifestyle Ideas", summary: "คัดไอเดียร้านอาหาร คาเฟ่ และกิจกรรมวันหยุดแบบอ่านเร็ว", priority_score: 69, recommended_action: "บันทึกสถานที่ที่สนใจไว้ดูต่อ", caption: "Lifestyle Ideas", image_prompt: null }, priorityScore: 69, telegramStatus: "mock_sent", errorMessage: null },
];

export const webNotifications: WebNotification[] = [
  { id: "noti_001", userId: "user_001", taskId: "task_004", taskRunId: "run_003", title: "Daily Email Digest พร้อมแล้ว", summary: "สรุปอีเมลรายวันพร้อมอ่าน", type: "Email Monitor", priorityScore: 88, isRead: false, createdAt: minutesAgo(34) },
  { id: "noti_002", userId: "user_001", taskId: "task_001", taskRunId: "run_001", title: "Morning Daily Brief พร้อมแล้ว", summary: "สรุปข่าวโลกและสภาพอากาศพร้อมอ่าน", type: "Daily Brief", priorityScore: 82, isRead: false, createdAt: minutesAgo(78) },
  { id: "noti_003", userId: "user_001", taskId: "task_003", taskRunId: "run_004", title: "US Stock News พร้อมอ่าน", summary: "สรุป US Stock News พร้อมอ่าน", type: "US Stock News", priorityScore: 84, isRead: true, createdAt: minutesAgo(1438) },
  { id: "noti_004", userId: "user_001", taskId: "task_006", taskRunId: "run_005", title: "Football Recap พร้อมแล้ว", summary: "สรุปฟุตบอลล่าสุดพร้อมอ่าน", type: "World Cup Recap", priorityScore: 72, isRead: false, createdAt: minutesAgo(239) },
];
