import type { WebNotification } from "@/types/notification";
import type { ScheduledTask } from "@/types/scheduled-task";
import type { TaskRun } from "@/types/task-run";

const now = new Date();
const minutesAgo = (minutes: number) => new Date(now.getTime() - minutes * 60_000).toISOString();
const minutesAfter = (minutes: number) => new Date(now.getTime() + minutes * 60_000).toISOString();

export const scheduledTasks: ScheduledTask[] = [
  {
    id: "task_001",
    userId: "user_001",
    name: "Morning Daily Brief",
    type: "Daily Brief",
    scheduleType: "Daily",
    cronExpression: "0 8 * * *",
    time: "08:00",
    timezone: "Asia/Bangkok",
    dataSources: ["News", "Weather API"],
    gptActions: ["Summarize", "Analyze Priority", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 70,
    status: "Active",
    isActive: true,
    lastRunAt: minutesAgo(80),
    nextRunAt: minutesAfter(520),
    createdAt: minutesAgo(4000),
    updatedAt: minutesAgo(80),
  },
  {
    id: "task_002",
    userId: "user_001",
    name: "สินค้าใหม่/น่าสนใจทั่วโลก",
    type: "Sale Monitor",
    scheduleType: "Hourly",
    cronExpression: "0 * * * *",
    time: null,
    timezone: "Asia/Bangkok",
    dataSources: ["Global Product Radar"],
    gptActions: ["Analyze Priority", "Generate Caption", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 70,
    status: "Active",
    isActive: true,
    lastRunAt: minutesAgo(17),
    nextRunAt: minutesAfter(43),
    createdAt: minutesAgo(3500),
    updatedAt: minutesAgo(17),
  },
  {
    id: "task_003",
    userId: "user_001",
    name: "Weekend Ideas Generator",
    type: "Weekend Ideas",
    scheduleType: "Weekly",
    cronExpression: "0 9 * * 6",
    time: "09:00",
    timezone: "Asia/Bangkok",
    dataSources: ["Weather API", "News", "Weekend Ideas"],
    gptActions: ["Summarize", "Recommend Action", "Generate Image Prompt"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 60,
    status: "Active",
    isActive: true,
    lastRunAt: minutesAgo(1440),
    nextRunAt: minutesAfter(2880),
    createdAt: minutesAgo(6000),
    updatedAt: minutesAgo(1440),
  },
  {
    id: "task_004",
    userId: "user_001",
    name: "Important Email Monitor",
    type: "Email Monitor",
    scheduleType: "Hourly",
    cronExpression: "*/30 * * * *",
    time: null,
    timezone: "Asia/Bangkok",
    dataSources: ["Gmail"],
    gptActions: ["Summarize", "Analyze Priority", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 80,
    status: "Active",
    isActive: true,
    lastRunAt: minutesAgo(36),
    nextRunAt: minutesAfter(24),
    createdAt: minutesAgo(7200),
    updatedAt: minutesAgo(36),
  },
  {
    id: "task_005",
    userId: "user_001",
    name: "Concert Alerts Near Me",
    type: "Concert Alerts",
    scheduleType: "Daily",
    cronExpression: "0 20 * * *",
    time: "20:00",
    timezone: "Asia/Bangkok",
    dataSources: ["Concert API"],
    gptActions: ["Summarize", "Analyze Priority", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 75,
    status: "Active",
    isActive: true,
    lastRunAt: minutesAgo(2880),
    nextRunAt: minutesAfter(1200),
    createdAt: minutesAgo(7000),
    updatedAt: minutesAgo(1000),
  },
  {
    id: "task_006",
    userId: "user_001",
    name: "Football Recap Nightly",
    type: "World Cup Recap",
    scheduleType: "Daily",
    cronExpression: "0 23 * * *",
    time: "23:00",
    timezone: "Asia/Bangkok",
    dataSources: ["Football API"],
    gptActions: ["Summarize", "Generate Caption", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 65,
    status: "Active",
    isActive: true,
    lastRunAt: minutesAgo(240),
    nextRunAt: minutesAfter(1140),
    createdAt: minutesAgo(9000),
    updatedAt: minutesAgo(240),
  },
  {
    id: "task_007",
    userId: "user_001",
    name: "Weekend Long Read Picker",
    type: "Weekend Long Read",
    scheduleType: "Weekly",
    cronExpression: "0 10 * * 6",
    time: "10:00",
    timezone: "Asia/Bangkok",
    dataSources: ["News", "Weekend Long Read"],
    gptActions: ["Summarize", "Analyze Priority", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 55,
    status: "Active",
    isActive: true,
    lastRunAt: minutesAgo(3000),
    nextRunAt: minutesAfter(3600),
    createdAt: minutesAgo(9400),
    updatedAt: minutesAgo(3000),
  },
];

export const taskRuns: TaskRun[] = [
  {
    id: "run_001",
    taskId: "task_001",
    status: "success",
    startedAt: minutesAgo(80),
    finishedAt: minutesAgo(79),
    rawInput: {
      news: ["AI tools update", "Market movement summary"],
      weather: "Bangkok is cloudy with afternoon rain risk.",
    },
    gptPrompt: "Summarize and prioritize today's updates for Nimbus Daily.",
    gptOutput: {
      title: "Morning Daily Brief",
      summary: "วันนี้มีข่าว AI และสภาพอากาศที่ควรรู้ เหมาะสำหรับจัดลำดับงานช่วงเช้า",
      priority_score: 82,
      recommended_action: "อ่านข่าว AI สำคัญก่อนเริ่มงาน และเตรียมแผนสำรองถ้าฝนตกช่วงเย็น",
      caption: "สรุปเช้านี้: AI อัปเดตแรง + ฝนมีโอกาสตกช่วงเย็น",
      image_prompt: "9:16 neon SaaS dashboard showing daily AI brief cards, dark glass UI, blue purple glow",
    },
    priorityScore: 82,
    telegramStatus: "mock_sent",
    errorMessage: null,
  },
  {
    id: "run_002",
    taskId: "task_002",
    status: "success",
    startedAt: minutesAgo(18),
    finishedAt: minutesAgo(17),
    rawInput: {
      products: ["AI wearable pin", "Portable e-ink dashboard", "GaN travel charging dock"],
    },
    gptPrompt: "Analyze global new and interesting products and recommend what is worth tracking.",
    gptOutput: {
      title: "สินค้าใหม่/น่าสนใจทั่วโลก",
      summary: "พบสินค้าและแกดเจ็ตน่าจับตาจากทั่วโลก เช่น AI wearable, e-ink dashboard และแท่นชาร์จ GaN สำหรับสายทำงาน/คอนเทนต์",
      priority_score: 84,
      recommended_action: "บันทึกไว้ใน Data Library และเลือก 1-2 ชิ้นไปทำรีวิว/คอนเทนต์ต่อ",
      caption: "🌍 Product Radar: ของใหม่ทั่วโลกที่น่าจับตาในสัปดาห์นี้",
      image_prompt: "9:16 futuristic global product radar dashboard, floating gadget cards, glassmorphism, neon cyan purple, premium tech UI",
    },
    priorityScore: 84,
    telegramStatus: "mock_sent",
    errorMessage: null,
  },
  {
    id: "run_003",
    taskId: "task_004",
    status: "success",
    startedAt: minutesAgo(36),
    finishedAt: minutesAgo(35),
    rawInput: {
      gmail: ["Vendor invoice reminder", "Security alert", "Meeting summary"],
    },
    gptPrompt: "Summarize important emails and rank priority.",
    gptOutput: {
      title: "Email Monitor Alert",
      summary: "พบอีเมลที่ควรตรวจวันนี้ 2 รายการ ได้แก่ Security alert และ invoice reminder",
      priority_score: 88,
      recommended_action: "เปิด Security alert ก่อน แล้วค่อยตรวจ invoice reminder",
      caption: "มีอีเมลสำคัญที่ควรดูวันนี้ Priority 88/100",
      image_prompt: null,
    },
    priorityScore: 88,
    telegramStatus: "mock_sent",
    errorMessage: null,
  },
  {
    id: "run_004",
    taskId: "task_003",
    status: "success",
    startedAt: minutesAgo(1440),
    finishedAt: minutesAgo(1439),
    rawInput: {
      weather: "Weekend weather is clear in the morning.",
      news: ["New cafe opening", "Outdoor market this weekend"],
    },
    gptPrompt: "Generate weekend ideas using weather and local updates.",
    gptOutput: {
      title: "Weekend Ideas",
      summary: "เสาร์นี้เหมาะกับคาเฟ่และตลาดกลางแจ้งช่วงเช้า เลี่ยงช่วงบ่ายถ้าอากาศร้อน",
      priority_score: 74,
      recommended_action: "เลือก 1 คาเฟ่ + 1 กิจกรรม outdoor แล้วบันทึกเป็น plan",
      caption: "ไอเดียเที่ยวเสาร์นี้: คาเฟ่เช้า + ตลาด outdoor แบบชิล ๆ",
      image_prompt: "9:16 lifestyle weekend plan card, modern dark glass dashboard, neon blue purple, Bangkok vibes",
    },
    priorityScore: 74,
    telegramStatus: "mock_sent",
    errorMessage: null,
  },
  {
    id: "run_005",
    taskId: "task_006",
    status: "success",
    startedAt: minutesAgo(240),
    finishedAt: minutesAgo(239),
    rawInput: {
      football: ["Team A vs Team B 2-1", "Team C vs Team D 0-0", "Team E vs Team F 3-2"],
    },
    gptPrompt: "Summarize football match results from Football API.",
    gptOutput: {
      title: "Football Recap",
      summary: "สรุปผลฟุตบอลล่าสุด 3 คู่ มีทั้งเกมท้ายเกมดราม่า เกมรับแน่น และแมตช์คัมแบ็กที่น่าสนใจ",
      priority_score: 72,
      recommended_action: "อ่านรายละเอียดเต็มใน Data Library แล้วเลือกคู่สำคัญไปทำโพสต์สรุปต่อ",
      caption: "⚽ สรุปบอลคืนนี้: มีทั้งประตูท้ายเกม เกมรับแน่น และคัมแบ็กสุดมัน",
      image_prompt: "9:16 football recap dashboard, scoreboard cards, stadium lights, modern sports UI",
    },
    priorityScore: 72,
    telegramStatus: "mock_sent",
    errorMessage: null,
  },
  {
    id: "run_006",
    taskId: "task_005",
    status: "success",
    startedAt: minutesAgo(2880),
    finishedAt: minutesAgo(2879),
    rawInput: {
      concerts: ["Indie Night Bangkok", "Synth Pop Live", "Jazz Weekend"],
    },
    gptPrompt: "Summarize new concert announcements and recommend actions.",
    gptOutput: {
      title: "Concert Alerts",
      summary: "มีคอนเสิร์ตที่น่าสนใจใกล้กรุงเทพ 3 รายการ เหมาะกับการบันทึกไว้ดูต่อ",
      priority_score: 78,
      recommended_action: "เลือกศิลปินที่สนใจแล้วตั้ง reminder สำหรับวันขายบัตร",
      caption: "คอนเสิร์ตน่าไปประจำสัปดาห์ มาแล้ว!",
      image_prompt: "9:16 neon concert alert poster, dark glass UI, purple blue light, Bangkok music vibe",
    },
    priorityScore: 78,
    telegramStatus: "mock_sent",
    errorMessage: null,
  },
  {
    id: "run_007",
    taskId: "task_007",
    status: "success",
    startedAt: minutesAgo(3000),
    finishedAt: minutesAgo(2998),
    rawInput: {
      articles: ["Long read about AI agents", "Deep dive on productivity systems"],
    },
    gptPrompt: "Pick weekend long reads and explain why they are worth reading.",
    gptOutput: {
      title: "Weekend Long Read Picks",
      summary: "คัดบทความอ่านยาว 2 เรื่องเกี่ยวกับ AI agents และ productivity systems เหมาะกับอ่านวันหยุด",
      priority_score: 69,
      recommended_action: "บันทึกบทความไว้ใน weekend reading list",
      caption: "บทความอ่านยาววันหยุด: AI agents + productivity systems",
      image_prompt: "9:16 cozy long read card, dark neon SaaS dashboard, blue purple glow, reading list UI",
    },
    priorityScore: 69,
    telegramStatus: "mock_sent",
    errorMessage: null,
  },
];

export const webNotifications: WebNotification[] = [
  {
    id: "noti_001",
    userId: "user_001",
    taskId: "task_004",
    taskRunId: "run_003",
    title: "มีอีเมลสำคัญต้องดู",
    summary: "GPT พบ Security alert และ invoice reminder ที่ควรตรวจวันนี้ Priority 88/100",
    type: "Email Monitor",
    priorityScore: 88,
    isRead: false,
    createdAt: minutesAgo(34),
  },
  {
    id: "noti_002",
    userId: "user_001",
    taskId: "task_001",
    taskRunId: "run_001",
    title: "Morning Daily Brief พร้อมแล้ว",
    summary: "GPT สรุปข่าว AI และสภาพอากาศให้แล้ว Priority 82/100",
    type: "Daily Brief",
    priorityScore: 82,
    isRead: false,
    createdAt: minutesAgo(78),
  },
  {
    id: "noti_003",
    userId: "user_001",
    taskId: "task_003",
    taskRunId: "run_004",
    title: "Weekend Ideas พร้อมใช้",
    summary: "แนะนำคาเฟ่ช่วงเช้าและกิจกรรม outdoor พร้อม prompt ภาพ 9:16",
    type: "Weekend Ideas",
    priorityScore: 74,
    isRead: true,
    createdAt: minutesAgo(1438),
  },
  {
    id: "noti_004",
    userId: "user_001",
    taskId: "task_006",
    taskRunId: "run_005",
    title: "Football Recap พร้อมแล้ว",
    summary: "สรุปฟุตบอลล่าสุดพร้อมไฮไลต์สำคัญ Priority 72/100",
    type: "World Cup Recap",
    priorityScore: 72,
    isRead: false,
    createdAt: minutesAgo(239),
  },
  {
    id: "noti_005",
    userId: "user_001",
    taskId: "task_002",
    taskRunId: "run_002",
    title: "สินค้าใหม่/น่าสนใจทั่วโลกพร้อมแล้ว",
    summary: "พบสินค้าและแกดเจ็ตน่าจับตาจากทั่วโลก Priority 84/100",
    type: "Sale Monitor",
    priorityScore: 84,
    isRead: false,
    createdAt: minutesAgo(4),
  },
  {
    id: "noti_006",
    userId: "user_001",
    taskId: "task_005",
    taskRunId: "run_006",
    title: "พบคอนเสิร์ตน่าสนใจ",
    summary: "มีรายการคอนเสิร์ตใกล้กรุงเทพที่ควรบันทึกไว้ดูต่อ Priority 78/100",
    type: "Concert Alerts",
    priorityScore: 78,
    isRead: true,
    createdAt: minutesAgo(2878),
  },
  {
    id: "noti_007",
    userId: "user_001",
    taskId: "task_007",
    taskRunId: "run_007",
    title: "Weekend Long Read คัดแล้ว",
    summary: "คัดบทความอ่านยาวเกี่ยวกับ AI agents และ productivity systems สำหรับวันหยุด",
    type: "Weekend Long Read",
    priorityScore: 69,
    isRead: true,
    createdAt: minutesAgo(2997),
  },
];
