import type { TaskTemplate } from "@/types/task-template";

export const taskTemplates: TaskTemplate[] = [
  {
    id: "morning-daily-brief",
    name: "Morning Daily Brief",
    description: "สรุปข่าว เทคโนโลยี และสภาพอากาศทุกเช้า พร้อม action ที่ควรทำต่อ",
    type: "Daily Brief",
    scheduleType: "Daily",
    cronExpression: "0 8 * * *",
    time: "08:00",
    timezone: "Asia/Bangkok",
    dataSources: ["News", "Weather API"],
    gptActions: ["Summarize", "Analyze Priority", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 70,
    tags: ["Morning", "News", "Weather"],
    icon: "☀️",
    recommendedFor: "คนที่อยากได้สรุปรายวันก่อนเริ่มงาน",
  },
  {
    id: "important-email-monitor",
    name: "Important Email Monitor",
    description: "คัดอีเมลสำคัญ วิเคราะห์ความเร่งด่วน และแจ้งเตือนเฉพาะรายการที่ต้องตอบ",
    type: "Email Monitor",
    scheduleType: "Hourly",
    cronExpression: "0 * * * *",
    time: null,
    timezone: "Asia/Bangkok",
    dataSources: ["Gmail"],
    gptActions: ["Summarize", "Analyze Priority", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 80,
    tags: ["Email", "Priority", "Work"],
    icon: "✉️",
    recommendedFor: "คนที่ต้องติดตามอีเมลงานสำคัญ",
  },
  {
    id: "sale-monitor",
    name: "Sale Monitor",
    description: "ติดตามสินค้าและโปรโมชันที่สนใจ แล้วให้ GPT สรุปว่าโปรคุ้มหรือควรรอ",
    type: "Sale Monitor",
    scheduleType: "Daily",
    cronExpression: "0 9 * * *",
    time: "09:00",
    timezone: "Asia/Bangkok",
    dataSources: ["Product Prices"],
    gptActions: ["Summarize", "Analyze Priority", "Generate Caption", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications"],
    minPriorityScore: 65,
    tags: ["Sale", "Affiliate", "Shopping"],
    icon: "🛒",
    recommendedFor: "สาย Affiliate หรือคนติดตามโปรลดราคา",
  },
  {
    id: "weather-morning-update",
    name: "Weather Morning Update",
    description: "สรุปสภาพอากาศตอนเช้า พร้อมคำแนะนำการเดินทางและกิจกรรมประจำวัน",
    type: "Daily Brief",
    scheduleType: "Daily",
    cronExpression: "30 6 * * *",
    time: "06:30",
    timezone: "Asia/Bangkok",
    dataSources: ["Weather API"],
    gptActions: ["Summarize", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 50,
    tags: ["Weather", "Morning", "Travel"],
    icon: "🌦️",
    recommendedFor: "คนที่อยากวางแผนเดินทางทุกเช้า",
  },
  {
    id: "football-recap",
    name: "Football Daily Recap",
    description: "สรุปผลบอล ตารางแข่ง และเรื่องเด่นของทีมที่ติดตาม",
    type: "World Cup Recap",
    scheduleType: "Daily",
    cronExpression: "0 7 * * *",
    time: "07:00",
    timezone: "Asia/Bangkok",
    dataSources: ["Football API"],
    gptActions: ["Summarize", "Generate Caption"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications"],
    minPriorityScore: 60,
    tags: ["Football", "Sport", "Recap"],
    icon: "⚽",
    recommendedFor: "คนที่อยากได้สรุปฟุตบอลแบบอ่านเร็ว",
  },
  {
    id: "public-alerts",
    name: "ประกาศสำคัญ / แจ้งเตือนรัฐ / BTS-MRT",
    description: "ติดตามประกาศหน่วยงานรัฐ บริการสาธารณะ และสถานะ BTS/MRT ขัดข้องแบบเร่งด่วน",
    type: "Public Alerts",
    scheduleType: "Daily",
    cronExpression: "*/20 6-22 * * *",
    time: null,
    timezone: "Asia/Bangkok",
    dataSources: ["Public Notices", "BTS/MRT Status", "NewsData.io"],
    gptActions: ["Summarize", "Analyze Priority", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 80,
    tags: ["Public Alerts", "Government", "BTS", "MRT"],
    icon: "📢",
    recommendedFor: "คนที่ต้องรู้ประกาศสำคัญและสถานะขนส่งก่อนออกเดินทาง",
  },
  {
    id: "travel-deals",
    name: "โปรเดินทาง / ตั๋วเครื่องบิน / โรงแรม",
    description: "ติดตามโปรตั๋วเครื่องบินในไทย ต่างประเทศที่เริ่มบินจากไทย ราคาห้องพัก โรงแรม และแพ็กเกจเที่ยวไทย",
    type: "Travel Deals",
    scheduleType: "Daily",
    cronExpression: "0 11 * * *",
    time: "11:00",
    timezone: "Asia/Bangkok",
    dataSources: ["Flight Deals", "Hotel Deals", "Travel Promotions", "NewsData.io"],
    gptActions: ["Summarize", "Analyze Priority", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 60,
    tags: ["Travel Deals", "Flights", "Hotels", "Thailand"],
    icon: "✈️",
    recommendedFor: "คนที่อยากติดตามโปรเดินทางและที่พักโดยไม่ปนกับโปรช้อปปิ้งทั่วไป",
  },
  {
    id: "concert-alerts",
    name: "Concert Alerts",
    description: "แจ้งเตือนข่าวคอนเสิร์ตและอีเวนต์ที่เกี่ยวกับศิลปินหรือแนวเพลงที่สนใจ",
    type: "Concert Alerts",
    scheduleType: "Daily",
    cronExpression: "0 18 * * *",
    time: "18:00",
    timezone: "Asia/Bangkok",
    dataSources: ["Concert API", "News"],
    gptActions: ["Summarize", "Analyze Priority", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 75,
    tags: ["Concert", "Event", "Alert"],
    icon: "🎫",
    recommendedFor: "คนที่ไม่อยากพลาดประกาศคอนเสิร์ต",
  },
  {
    id: "custom-ai-task",
    name: "Custom AI Task",
    description: "Template เปล่าสำหรับงาน AI ที่อยากตั้งเอง เช่น สรุปเว็บ ข่าวเฉพาะเรื่อง หรือ reminder แบบกำหนดเอง",
    type: "Custom",
    scheduleType: "Daily",
    cronExpression: "0 8 * * *",
    time: "08:00",
    timezone: "Asia/Bangkok",
    dataSources: ["News"],
    gptActions: ["Summarize", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications"],
    minPriorityScore: 70,
    tags: ["Custom", "AI", "Starter"],
    icon: "🤖",
    recommendedFor: "ใช้เป็นจุดเริ่มต้นสำหรับ workflow ของตัวเอง",
  },
];

export function getTaskTemplateById(id: string) {
  return taskTemplates.find((template) => template.id === id) ?? null;
}
